[package]
name = "gun"
description = "The Gun database, in Rust"
authors = [
  "Artemciy <artemciy@gmail.com>",
  "GiraffeKey <giraffekey@tutanota.com>",
]
version = "0.1.1"
edition = "2018"
license = "MIT"
keywords = ["p2p", "graph", "offline-first", "crdt", "database"]
#documentation = "docs.rs.."
repository = "https://github.com/ArtemGr/gun"

[lib]
name = "gun"
path = "src/gun.rs"

[dependencies]
anyhow = "1.0"
fnv = "1.0"
log = "0.4"
rand = "0.7"
serde_json = "1.0"
substring = "1.4"
tungstenite = "0.11"
uuid = { version = "0.8", features = ["v4"] }

[features]
#no_std = ["bare-io"]

[dev-dependencies]
env_logger = "0.8"
